language: java

jdk:
  - oraclejdk8

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
  - echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust


after_success:
  - ./cd/deploy.sh